apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: "myjob15"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: elsonrodriguez/mytfmodel:1.9
              name: tensorflow
              imagePullPolicy: Always
              args: ["python", "/opt/model.py", "--data_dir=/tmp/data", "--train_dir=/tmp/train", "--download=true"] 
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: elsonrodriguez/mytfserver:1.5
              name: tensorflow
              imagePullPolicy: Always
          restartPolicy: OnFailure
    - replicas: 2
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: elsonrodriguez/mytfserver:1.5
              name: tensorflow
              imagePullPolicy: Always
          restartPolicy: OnFailure
