apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tf-slim-
spec:
  entrypoint: tf-slim
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: datasets-image
      # default
      value: gcr.io/constant-cubist-173123/tf_workflow:nan_workflow
  templates:
  - name: tf-slim
    steps:
    - - name: prepare-datasets
        template: datasets

  - name: datasets
    container:
      image: "{{workflow.parameters.datasets-image}}"
      command: [bash]
      source: |
        cd /notebooks/models/research/slim
        python download_and_convert_data.py \
          --dataset_name=flowers \
          --dataset_dir="${DATA_DIR}"
