version: 2
jobs:
  build:
    docker:
      - image: nervana/circleci:master
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build container
          command: |
            cd tensorflow
            build_container
  argo:
    docker:
      - image: nervana/circleci:master
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run argo
          command: |
            export KUBE_CONFIG="${GKE_KUBECONFIG_ARGO}"
            mkdir -p "${HOME}/.kube"
            echo "${KUBE_CONFIG}" | base64 --decode > "${HOME}/.kube/config"
            id=$(argo submit -o json -n argo --serviceaccount argo \
                   -p datasets-image="gcr.io/constant-cubist-173123/tf_workflow:${CIRCLE_SHA1}" \
                   -p aws-access-key-id="${AWS_ACCESS_KEY_ID}" \
                   -p aws-secret-access-key="${AWS_SECRET_ACCESS_KEY}" \
                   -p job-name="job-${CIRCLE_BUILD_NUM}" \
                   tfargo.yaml | jq -r ".metadata.name")
            argo wait -n argo "${id}"
            argo get -n argo "${id}" | grep -v aws
workflows:
  version: 2
  test:
    jobs:
      - build
      - argo:
          requires:
          - build
