version: 2
jobs:
  build:
    docker:
      - image: nervana/circleci:master
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build container
          command: |
            cd tensorflow
            build_container
  argo:
    docker:
      - image: nervana/circleci:nan_argo
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run argo
          command: |
            export KUBE_CONFIG="${GKE_KUBECONFIG_ARGO}"
            mkdir -p "${HOME}/.kube"
            echo "${KUBE_CONFIG}" | base64 --decode > "${HOME}/.kube/config"
            argo list
workflows:
  version: 2
  test:
    jobs:
      - build
      - argo
